"""added "is_loaded" to file model and "location_on_server" renamed to "location”

Revision ID: ce640faf35d3
Revises: f3f6603d88d8
Create Date: 2023-04-08 22:34:58.626432

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'ce640faf35d3'
down_revision = 'f3f6603d88d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('file', sa.Column('is_loaded', sa.Boolean(), nullable=False))
    op.drop_column('file', 'location_on_server')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('location_on_server', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('file', 'is_loaded')
    op.drop_column('file', 'location')
    # ### end Alembic commands ###
